[env]
DEBUG_PATH = "target/x86_64-pc-windows-msvc/debug"
RELEASE_PATH = "target/x86_64-pc-windows-msvc/release"

[config]
default_to_workspace = false

[tasks.vm]
script = [
    "cd vm-build",
    "%HOMEDRIVE%/%HOMEPATH%/.cargo/bin/cargo.exe +nightly mommy b --release --target x86_64-pc-windows-msvc",
]

[tasks.vmx32]
script = [
    "cd vm-build",
    "%HOMEDRIVE%/%HOMEPATH%/.cargo/bin/cargo.exe +nightly mommy b --release --target i686-pc-windows-msvc",
]

[tasks.test]
toolchain = "nightly"
command = "cargo"
# args = ["test", "--all-features"]
args = ["test", "--all-features"]
# "--", "--test-threads=1"
install_crate = false
